<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>A work in progress--improves over the existing in that it populates symbols, and handles comments more gracefully.</string>
	<key>fileTypes</key>
	<array>
		<string>sas</string>
	</array>
	<key>name</key>
	<string>Sas Program</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i:\b(if|while|until|for|do|end|then|else|run|quit|cancel)\b)</string>
			<key>name</key>
			<string>keyword.control.sas</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.sas</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:\b((data|set|merge)\s+(\w+))\b)</string>
			<key>name</key>
			<string>keyword.other.sas</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.sas</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(%(macro|mend|do|if|then|end|while|until|goto|include)))\s*(\w*)</string>
			<key>name</key>
			<string>keyword.other.sas</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:\bproc\s*sql\b.*)</string>
			<key>comment</key>
			<string>Looks like for this to work there must be a *name* as well as the patterns/include bit.</string>
			<key>end</key>
			<string>(?i:\bquit\s*;)</string>
			<key>name</key>
			<string>sql.block.sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#star_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hanging_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(by|label|format)\b)</string>
			<key>name</key>
			<string>keyword.datastep.sas</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.sas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:\b(proc (\w+))\b)</string>
			<key>name</key>
			<string>meta.function-call.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(_n_|_error_)\b)</string>
			<key>name</key>
			<string>variable.language.sas</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#star_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hanging_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\+/*^]</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(eq|ne|gt|ge|lt|le|=|!=|^=))\b</string>
			<key>name</key>
			<string>keyword.operator.assignment.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:['"]\d{1,2}(jan|feb|apr|may|jun|jul|aug|sep|oct|nov|dec)\d{2,4}['"]d)</string>
			<key>name</key>
			<string>constant.date.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.+'</string>
			<key>name</key>
			<string>string.quoted.single.sas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>".+"</string>
			<key>name</key>
			<string>string.quoted.double.roy</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>hanging_comment</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=;)\s*\*</string>
			<key>comment</key>
			<string>This should handle 'hanging' comments where there is executable code to the left of the comment.</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>comment.block.sas</string>
		</dict>
		<key>star_comment</key>
		<dict>
			<key>begin</key>
			<string>^\s*\*</string>
			<key>comment</key>
			<string>This should handle simple comments where star is the first non-whitespace char on the line.</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>comment.block.sas</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sas</string>
	<key>uuid</key>
	<string>7e721b1e-6265-4865-bc4b-308d49affba1</string>
</dict>
</plist>
